name: Validar Origem do PR

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar se a branch de origem é a develop
        if: github.head_ref != 'develop'
        run: |
          echo "Erro: Pull Requests para a branch 'main' só são permitidos a partir da 'develop'."
          echo "Sua branch de origem atual é: ${{ github.head_ref }}"
          exit 1